[package]
name = "aosrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codepage-437 = "0.1.0"
colored = "2.0.0"
enet-sys = "1.0.1"