[package]
name = "aosrs"
version = "1.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codepage-437 = "0.1.0"
colored = "2.0.0"
enet-sys = "1.0.1"
flate2 = "1.0"
image = "0.25.5"
bit-vec = "0.8.0"